name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install
        working-directory: ./HomeAssistantToContenful.UI/homeassistanttocontentful-ui
      - run: yarn generate
        working-directory: ./HomeAssistantToContenful.UI/homeassistanttocontentful-ui
        env:
          CTF_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CTF_CDA_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 sync ./HomeAssistantToContenful.UI/homeassistanttocontentful-ui/dist s3://machathon-ui
      - run: aws cloudfront create-invalidation --distribution-id cloudfrontId --paths '/*'



